device: cuda
model:
  arch: Unet
  encoder_name: resnet18
  encoder_weights: imagenet
  in_channels: 3
  classes: 1
train:
  epoch: 5
  # train_step: 100
  # val_every_n_step: 50
  save_step: 1000
  optim:
    weight_decay: 0.001
    lr_max: 2e-3

#train: 45174 samples
#val: 21634 samples